import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9fb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#57657b',
        'error-container': '#ffdad6',
        'primary-container': '#282f44',
        'secondary-container': '#d5e3fd',
        'surface-container': '#eceef0',
        'surface-tint': '#565e74',
        'tertiary': '#002113',
        'on-tertiary-container': '#00ad78',
        'on-error-container': '#93000a',
        'background': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'on-primary-fixed-variant': '#3f465c',
        'on-primary-fixed': '#131b2e',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#002113',
        'tertiary-fixed': '#6ffbbe',
        'surface-container-low': '#f2f4f6',
        'primary-fixed': '#dae2fd',
        'on-secondary-fixed-variant': '#3a485c',
        'secondary-fixed': '#d5e3fd',
        'outline-variant': '#c6c5d4',
        'error': '#ba1a1a',
        'secondary': '#515f74',
        'primary': '#131b2e',
        'surface-container-highest': '#e0e3e5',
        'on-surface-variant': '#454652',
        'on-tertiary-fixed-variant': '#005236',
        'on-error': '#ffffff',
        'on-background': '#191c1e',
        'surface-container-high': '#e6e8ea',
        'on-surface': '#191c1e',
        'primary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#0d1c2f',
        'surface-bright': '#f7f9fb',
        'tertiary-container': '#003824',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#bec6e0',
        'on-primary-container': '#8f97b0',
        'inverse-surface': '#2d3133',
        'outline': '#767683',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#b9c7e0',
        'surface-variant': '#e0e3e5',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        body: ['var(--font-inter)', 'Inter', 'sans-serif'],
        label: ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
